name: OWL CI workflow

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: code

      - name: Install Ubuntu dependencies
        working-directory: ./code
        run: |
          sudo apt-get update -y
          sudo apt-get install -y m4 wget unzip aspcud libshp-dev libplplot-dev gfortran pkg-config git

      - name: Install OCaml and OPAM
        working-directory: ./code
        run: |
          sudo apt-get install -y ocaml
          sudo add-apt-repository ppa:avsm/ppa
          sudo apt-get update -y
          sudo apt-get install opam
          opam init
          eval `opam env`
          opam switch create 4.11.1
          eval `opam env

      - name: Install Owl dependencies
        working-directory: ./code
        run: |
          opam install dune
          make