name: OWL CI workflow

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: code

      - name: Install dependencies
        working-directory: ./code
        run: |
          sudo apt-get update -y
          sudo apt-get install -y m4 wget unzip aspcud libshp-dev libplplot-dev gfortran pkg-config git ocaml
          add-apt-repository ppa:avsm/ppa && apt update && apt install opam
          opam init
          eval `opam env`
          opam switch create 4.11.1
          eval `opam env
